#!/usr/bin/env node
/**
 * Design-token build (zero dependencies).
 *
 *   tokens/primitive.json  ─┐
 *   tokens/semantic.json   ─┼─► dist/tokens.css          CSS custom properties (light + dark)
 *   tokens/weather.json    ─┘   dist/tokens.ts           typed constants for the web app
 *                               dist/tokens.json         flat resolved values per mode
 *                               dist/weather-scales.json colour scales + thresholds (web + backend)
 *
 * Generated files are also copied to the consumers:
 *   frontend/src/design/generated/   and   backend/app/data/weather_scales.json
 *
 * Usage:  node scripts/build-tokens.mjs [--check]
 *   --check  exit 1 if any generated file is stale (used in CI)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO = resolve(ROOT, '..');
const CHECK = process.argv.includes('--check');
const MODE_KEY = 'th.weather.modes';

const read = (f) => JSON.parse(readFileSync(join(ROOT, 'tokens', f), 'utf8'));
const primitive = read('primitive.json');
const semantic = read('semantic.json');
const weather = read('weather.json');

/** Walk a DTCG tree and collect tokens: { path, type, value, dark, description } */
function collect(tree, path = [], inheritedType) {
  const out = [];
  const type = tree.$type ?? inheritedType;
  if ('$value' in tree) {
    out.push({
      path: path.join('.'),
      type,
      value: tree.$value,
      dark: tree.$extensions?.[MODE_KEY]?.dark,
      description: tree.$description,
    });
    return out;
  }
  for (const [k, v] of Object.entries(tree)) {
    if (k.startsWith('$') || typeof v !== 'object' || v === null) continue;
    out.push(...collect(v, [...path, k], type));
  }
  return out;
}

const all = [...collect(primitive), ...collect(semantic)];
const byPath = new Map(all.map((t) => [t.path, t]));

function resolveValue(value, mode = 'light', depth = 0) {
  if (depth > 10) throw new Error(`reference cycle near ${JSON.stringify(value)}`);
  if (typeof value === 'string') {
    const whole = value.match(/^\{([^}]+)\}$/);
    if (whole) {
      const ref = byPath.get(whole[1]);
      if (!ref) throw new Error(`unknown token reference ${value}`);
      const v = mode === 'dark' && ref.dark !== undefined ? ref.dark : ref.value;
      return resolveValue(v, mode, depth + 1);
    }
    return value;
  }
  if (Array.isArray(value)) return value.map((v) => resolveValue(v, mode, depth + 1));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(v, mode, depth + 1)]));
  }
  return value;
}

const cssName = (path) => '--' + path.replace(/\./g, '-').replace(/_/g, '-');

function cssValue(token, value) {
  switch (token.type) {
    case 'fontFamily':
      return value.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'typography':
      return null; // emitted as utility classes instead
    default:
      return String(value);
  }
}

// ---------------------------------------------------------------- CSS
const lightVars = [];
const darkVars = [];
const typeClasses = [];
for (const t of all) {
  if (t.type === 'typography') {
    const v = resolveValue(t.value);
    const name = t.path.split('.').pop();
    typeClasses.push(
      `.text-${name} {\n` +
        `  font-family: ${cssValue({ type: 'fontFamily' }, v.fontFamily)};\n` +
        `  font-size: ${v.fontSize};\n  font-weight: ${v.fontWeight};\n  line-height: ${v.lineHeight};\n` +
        (v.letterSpacing ? `  letter-spacing: ${v.letterSpacing};\n` : '') +
        (name === 'data' || name === 'display' ? '  font-variant-numeric: tabular-nums;\n' : '') +
        '}',
    );
    continue;
  }
  const light = cssValue(t, resolveValue(t.value, 'light'));
  lightVars.push(`  ${cssName(t.path)}: ${light};`);
  if (t.dark !== undefined) darkVars.push(`  ${cssName(t.path)}: ${cssValue(t, resolveValue(t.dark, 'dark'))};`);
}

const header = '/* Generated by design-system/scripts/build-tokens.mjs – do not edit. */\n';
const css =
  header +
  `:root {\n  color-scheme: light;\n${lightVars.join('\n')}\n}\n\n` +
  `:root[data-theme="dark"] {\n  color-scheme: dark;\n${darkVars.join('\n')}\n}\n\n` +
  `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n    color-scheme: dark;\n` +
  darkVars.map((l) => '  ' + l).join('\n') +
  `\n  }\n}\n\n` +
  typeClasses.join('\n\n') +
  '\n';

// ---------------------------------------------------------------- JSON / TS
const flat = { light: {}, dark: {} };
for (const t of all) {
  flat.light[t.path] = resolveValue(t.value, 'light');
  flat.dark[t.path] = resolveValue(t.dark ?? t.value, 'dark');
}

const weatherResolved = resolveValue(stripMeta(weather));
function stripMeta(o) {
  if (Array.isArray(o)) return o.map(stripMeta);
  if (o && typeof o === 'object') {
    return Object.fromEntries(
      Object.entries(o)
        .filter(([k]) => k !== '$description')
        .map(([k, v]) => [k, stripMeta(v)]),
    );
  }
  return o;
}

const ts =
  '/* Generated by design-system/scripts/build-tokens.mjs – do not edit. */\n' +
  `export const tokens = ${JSON.stringify(flat, null, 2)} as const;\n\n` +
  'export type TokenPath = keyof typeof tokens.light;\n\n' +
  "/** CSS custom-property reference for a token, e.g. cssVar('color.bg.canvas'). */\n" +
  "export const cssVar = (path: TokenPath): string => `var(--${path.replace(/[._]/g, '-')})`;\n\n" +
  `export const weatherScales = ${JSON.stringify(weatherResolved, null, 2)} as const;\n`;

const outputs = {
  'dist/tokens.css': css,
  'dist/tokens.json': JSON.stringify(flat, null, 2) + '\n',
  'dist/tokens.ts': ts,
  'dist/weather-scales.json': JSON.stringify(weatherResolved, null, 2) + '\n',
};
const copies = {
  [join(REPO, 'frontend/src/design/generated/tokens.css')]: css,
  [join(REPO, 'frontend/src/design/generated/tokens.ts')]: ts,
  [join(REPO, 'backend/app/data/weather_scales.json')]: outputs['dist/weather-scales.json'],
};

let stale = [];
for (const [file, content] of [...Object.entries(outputs).map(([f, c]) => [join(ROOT, f), c]), ...Object.entries(copies)]) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  if (CHECK) {
    stale.push(file);
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file.replace(REPO + '/', '')}`);
  }
}
if (CHECK && stale.length) {
  console.error('Generated token files are stale – run `node design-system/scripts/build-tokens.mjs`:\n  ' + stale.join('\n  '));
  process.exit(1);
}
console.log(`${all.length} tokens, ${Object.keys(weather.scales).length} weather scales, ${Object.keys(weather.categories).length} categories`);
